version: "3.9"

services:
  backend:
    build: ./backend
    container_name: travelmemory_backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - PORT=3001
    depends_on:
      - database
    networks:
      - tmapp_network

  frontend:
    build: ./frontend
    container_name: travelmemory_frontend 
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=https://3001-port-rqjpcay5khml3qoq.labs.kodekloud.com/
    depends_on:
      - backend
    networks:
      - tmapp_network
  
  database:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tmapp_network

volumes:
  mongo-data:

networks:
  tmapp_network:
    driver: bridge